# Generated by Django 5.2.5 on 2025-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_address',
            new_name='clinicAddress',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='fullName',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
